POST http://localhost:4000/api/sender
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "Test McTestFace",
  "password": "password"
}

###

POST http://localhost:4000/api/parcel
Content-Type: application/json
Authorization: Basic test@test.com:password

{
  "address": "Main Street 123", "dimensions": {
    "height": 10,
    "width": 20,
    "depth": 15
  }
}

###

GET http://localhost:4000/api/parcel/655d4a00faa56e601d101a54
Authorization: Basic test@test.com:password
